league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        encryption_key_type:  plain
        access_token_ttl:     PT1H
        refresh_token_ttl:    P7D
        auth_code_ttl:        PT10M
        enable_refresh_token_grant: true
        enable_auth_code_grant: true
        require_code_challenge_for_public_clients: true
        persist_access_token: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['user', 'game']
        default: ['user', 'game']
    persistence:
        # doctrine: 
        #   entity_manager: default
        in_memory: ~

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
