// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file proto/rating.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRatingRequest, GetRatingResponse, SetRatingRequest, SetRatingResponse } from "./rating_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service RatingService
 */
export const RatingService = {
  typeName: "RatingService",
  methods: {
    /**
     * @generated from rpc RatingService.GetRating
     */
    getRating: {
      name: "GetRating",
      I: GetRatingRequest,
      O: GetRatingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RatingService.SetRating
     */
    setRating: {
      name: "SetRating",
      I: SetRatingRequest,
      O: SetRatingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

