<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rating.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GetRatingRequest</code>
 */
class GetRatingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string game_id = 1 [json_name = "gameId"];</code>
     */
    protected $game_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $game_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rating::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string game_id = 1 [json_name = "gameId"];</code>
     * @return string
     */
    public function getGameId()
    {
        return $this->game_id;
    }

    /**
     * Generated from protobuf field <code>string game_id = 1 [json_name = "gameId"];</code>
     * @param string $var
     * @return $this
     */
    public function setGameId($var)
    {
        GPBUtil::checkString($var, True);
        $this->game_id = $var;

        return $this;
    }

}

